# Hardware config generated by 'nixos-generate-config'
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/684daa8f-853a-4327-95d4-89339aef4393";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-86fadf9e-9e07-425a-855c-95ef7bd27e3f".device = "/dev/disk/by-uuid/86fadf9e-9e07-425a-855c-95ef7bd27e3f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/82F3-8F2E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f7dbf85a-3e2b-4345-88a5-2bfa4b946dd0";}
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
